networks:
  app-network:
    driver: bridge

services:
  gestion_caja:
    build: ./servicios/gestion_caja
    ports:
      - "4004:4004"
    environment:
      - NODE_ENV=development
      - PORT=4004
    env_file:
      - ./servicios/gestion_caja/.env
    networks:
      - app-network

  gestion_pagos:
    build: ./servicios/gestion_pagos
    ports:
      - "4005:4005"
    environment:
      - NODE_ENV=development
      - PORT=4005
    networks:
      - app-network

  facturacion:
    build: ./servicios/facturacion
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=development
      - PORT=4002
    env_file:
      - ./servicios/facturacion/.env
    networks:
      - app-network

  pagos_proveedores:
    build: ./servicios/pagos_proveedores
    ports:
      - "4006:4006"
    environment:
      - NODE_ENV=development
      - PORT=4006
    env_file:
      - ./servicios/pagos_proveedores/.env
    networks:
      - app-network