# 1. Imagen base de Node.js
FROM node:20

# 2. Carpeta de trabajo
WORKDIR /servicios

# 3. Copiar archivos de dependencias
COPY package*.json ./

# 4. Instalar dependencias
RUN npm install

# 5. Copiar el código del microservicio
COPY . .

# 6. Puerto del microservicio
EXPOSE 4002

# 7. Ejecutar la aplicación
CMD ["node", "src/index.js"]